services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - DB_URL=jdbc:mysql://mysql:3306/kea
      - DB_DRIVER=com.mysql.cj.jdbc.Driver
      - DB_USER=kea
      - DB_PASSWORD=kea
      - CHATGPT_API_KEY=dummy
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kea
      MYSQL_DATABASE: kea
      MYSQL_USER: kea
      MYSQL_PASSWORD: kea
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
