name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  whatever:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          java-version: "24"
          distribution: "temurin"
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
      - run: mvn test
      - run: docker build . --tag hej-github:test
      - run: |
          docker run -d --name test-container -p 8080:8080 hej-github:test
          sleep 30
          curl -f http://localhost:8080/healthz || exit 1
          docker stop test-container
          docker rm test-container
